// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantManager.Data;

#nullable disable

namespace RestaurantManager.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250509084559_AddOrderDateRemovedRequiredFromIdUpdateICollection")]
    partial class AddOrderDateRemovedRequiredFromIdUpdateICollection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RestaurantManager.Models.DietaryTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("dietary_tag");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Vegan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gluten-Free"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dairy-Free"
                        });
                });

            modelBuilder.Entity("RestaurantManager.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("INTEGER")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_available");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("REAL")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("menu_item");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "MainCourse",
                            Description = "A delicious vegan pizza with gluten-free crust.",
                            IsAvailable = true,
                            Name = "Vegan Pizza",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 2,
                            Category = "MainCourse",
                            Description = "A tasty chicken wrap with fresh vegetables.",
                            IsAvailable = true,
                            Name = "Chicken Wrap",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 3,
                            Category = "MainCourse",
                            Description = "A classic Caesar salad with creamy dressing.",
                            IsAvailable = true,
                            Name = "Caesar Salad",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = 4,
                            Category = "MainCourse",
                            Description = "Hearty beef lasagna with mozzarella cheese.",
                            IsAvailable = true,
                            Name = "Beef Lasagna",
                            Price = 13.49m
                        },
                        new
                        {
                            Id = 5,
                            Category = "MainCourse",
                            Description = "Grilled salmon with lemon butter sauce.",
                            IsAvailable = true,
                            Name = "Grilled Salmon",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Appetizer",
                            Description = "Toasted garlic bread with herbs.",
                            IsAvailable = true,
                            Name = "Garlic Bread",
                            Price = 4.99m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Appetizer",
                            Description = "Tomatoes, garlic, basil on toasted baguette.",
                            IsAvailable = true,
                            Name = "Bruschetta",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Appetizer",
                            Description = "Mushrooms filled with cheese and herbs.",
                            IsAvailable = true,
                            Name = "Stuffed Mushrooms",
                            Price = 6.99m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Appetizer",
                            Description = "Vegetable spring rolls with sweet chili sauce.",
                            IsAvailable = true,
                            Name = "Spring Rolls",
                            Price = 5.49m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Appetizer",
                            Description = "Loaded nachos with cheese and jalapeños.",
                            IsAvailable = true,
                            Name = "Nachos",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Dessert",
                            Description = "Rich chocolate cake with fudge frosting.",
                            IsAvailable = true,
                            Name = "Chocolate Cake",
                            Price = 6.99m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Dessert",
                            Description = "Creamy cheesecake with a graham cracker crust.",
                            IsAvailable = true,
                            Name = "Cheesecake",
                            Price = 6.49m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Dessert",
                            Description = "Vanilla ice cream with toppings.",
                            IsAvailable = true,
                            Name = "Ice Cream Sundae",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Dessert",
                            Description = "Italian dessert with coffee and mascarpone.",
                            IsAvailable = true,
                            Name = "Tiramisu",
                            Price = 7.49m
                        },
                        new
                        {
                            Id = 15,
                            Category = "Dessert",
                            Description = "Fresh seasonal fruit medley.",
                            IsAvailable = true,
                            Name = "Fruit Salad",
                            Price = 4.99m
                        },
                        new
                        {
                            Id = 16,
                            Category = "Beverage",
                            Description = "Freshly brewed coffee.",
                            IsAvailable = true,
                            Name = "Coffee",
                            Price = 2.99m
                        },
                        new
                        {
                            Id = 17,
                            Category = "Beverage",
                            Description = "Chilled black tea with lemon.",
                            IsAvailable = true,
                            Name = "Iced Tea",
                            Price = 2.99m
                        },
                        new
                        {
                            Id = 18,
                            Category = "Beverage",
                            Description = "Blended fruit smoothie with yogurt.",
                            IsAvailable = true,
                            Name = "Smoothie",
                            Price = 4.99m
                        },
                        new
                        {
                            Id = 19,
                            Category = "Beverage",
                            Description = "Fresh squeezed lemonade.",
                            IsAvailable = true,
                            Name = "Lemonade",
                            Price = 3.49m
                        },
                        new
                        {
                            Id = 20,
                            Category = "Beverage",
                            Description = "Choice of Coke, Sprite, or Root Beer.",
                            IsAvailable = true,
                            Name = "Soda",
                            Price = 2.49m
                        });
                });

            modelBuilder.Entity("RestaurantManager.Models.MenuItemDietaryTag", b =>
                {
                    b.Property<int>("MenuItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("menu_item_id");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tag_id");

                    b.HasKey("MenuItemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("menu_item_dietary_tag");

                    b.HasData(
                        new
                        {
                            MenuItemId = 1,
                            TagId = 1
                        },
                        new
                        {
                            MenuItemId = 1,
                            TagId = 2
                        },
                        new
                        {
                            MenuItemId = 2,
                            TagId = 3
                        });
                });

            modelBuilder.Entity("RestaurantManager.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("AddressId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("address_id");

                    b.Property<decimal?>("DeliveryFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("REAL")
                        .HasColumnName("delivery_fee");

                    b.Property<string>("DeliveryInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("delivery_instructions");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("order_date");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reservation_id");

                    b.Property<DateTime?>("ScheduledTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("scheduled_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("REAL")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Tax")
                        .HasPrecision(10, 2)
                        .HasColumnType("REAL")
                        .HasColumnName("tax");

                    b.Property<decimal>("TipAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("REAL")
                        .HasColumnName("tip_amount");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("REAL")
                        .HasColumnName("total_amount");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_type");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("UserId");

                    b.ToTable("order");
                });

            modelBuilder.Entity("RestaurantManager.Models.OrderMenuItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_id");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("menu_item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.HasKey("OrderId", "MenuItemId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("order_menu_item");
                });

            modelBuilder.Entity("RestaurantManager.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("GuestCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("guest_count");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<DateTime>("ReservationDateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("reservation_datetime");

                    b.Property<int>("ReservationStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reservation_status");

                    b.Property<int>("TableNumber")
                        .HasColumnType("INT")
                        .HasColumnName("table_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("reservation");
                });

            modelBuilder.Entity("RestaurantManager.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("DietaryNotes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("dietary_notes");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("password_salt");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("phone");

                    b.Property<int>("RewardsPoints")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rewards_points");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("INTEGER")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Email = "admin@gmail.com",
                            FirstName = "Admin",
                            LastName = "Test",
                            PasswordHash = "+1fzEaaKIt+hxB8eZ5RK6sywJXqY5Qkn7CxNoG6ckxc=",
                            PasswordSalt = "hHA0qDG/iJSbc9PEUXJ8UQ==",
                            Phone = "111-111-1111",
                            RewardsPoints = 0,
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("RestaurantManager.Models.UserAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("address_line_1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("address_line_2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("country");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("province");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_address");
                });

            modelBuilder.Entity("RestaurantManager.Models.UserDietaryTag", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tag_id");

                    b.HasKey("UserId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("user_dietary_tag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantManager.Models.MenuItemDietaryTag", b =>
                {
                    b.HasOne("RestaurantManager.Models.MenuItem", "MenuItem")
                        .WithMany("MenuItemDietaryTags")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantManager.Models.DietaryTag", "DietaryTag")
                        .WithMany("MenuItemDietaryTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietaryTag");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("RestaurantManager.Models.Order", b =>
                {
                    b.HasOne("RestaurantManager.Models.UserAddress", "UserAddress")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("RestaurantManager.Models.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId");

                    b.HasOne("RestaurantManager.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("User");

                    b.Navigation("UserAddress");
                });

            modelBuilder.Entity("RestaurantManager.Models.OrderMenuItem", b =>
                {
                    b.HasOne("RestaurantManager.Models.MenuItem", "MenuItem")
                        .WithMany("OrderMenuItems")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantManager.Models.Order", "Order")
                        .WithMany("OrderMenuItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantManager.Models.Reservation", b =>
                {
                    b.HasOne("RestaurantManager.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantManager.Models.UserAddress", b =>
                {
                    b.HasOne("RestaurantManager.Models.User", "User")
                        .WithMany("UserAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantManager.Models.UserDietaryTag", b =>
                {
                    b.HasOne("RestaurantManager.Models.DietaryTag", "DietaryTag")
                        .WithMany("UserDietaryTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantManager.Models.User", "User")
                        .WithMany("UserDietaryTags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietaryTag");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantManager.Models.DietaryTag", b =>
                {
                    b.Navigation("MenuItemDietaryTags");

                    b.Navigation("UserDietaryTags");
                });

            modelBuilder.Entity("RestaurantManager.Models.MenuItem", b =>
                {
                    b.Navigation("MenuItemDietaryTags");

                    b.Navigation("OrderMenuItems");
                });

            modelBuilder.Entity("RestaurantManager.Models.Order", b =>
                {
                    b.Navigation("OrderMenuItems");
                });

            modelBuilder.Entity("RestaurantManager.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reservations");

                    b.Navigation("UserAddresses");

                    b.Navigation("UserDietaryTags");
                });
#pragma warning restore 612, 618
        }
    }
}
